obstacle_range: 1.5
raytrace_range: 8.5
footprint: [[0.21, 0.22], [0.21, -0.22], [-0.21, -0.22], [-0.21, 0.22]]
map_topic: /map
subscribe_to_updates: true
global_frame: map
robot_base_frame: ebot_base
always_send_full_costmap: true
static_layer:
    map_topic: /map
    subscribe_to_updates: true
plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
inflation_layer:
    inflation_radius: 0.1
obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: ebot_base, data_type: LaserScan, topic: /ebot/laser/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 1.5, obstacle_range: 6.0, raytrace_range: 8.5}
    depth: {data_type: PointCloud2,topic: /zed2/point_cloud/cloud_registered,marking: true, clearing: true,min_obstacle_height: 0.25,max_obstacle_height: 10}

    depth1: {data_type: PointCloud2,topic: /extract_plane_indices/output,marking: true, clearing: true,min_obstacle_height: 0.3,max_obstacle_height: 10}
