# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
local_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  transform_tolerance: 0.5
  update_frequency: 5.0
  publish_frequency: 1.0
  rolling_window: true
  static_map: false
  always_send_full_costmap: true

  resolution: 0.1
  width: 3.0
  height: 3.0

  plugins: 
    - {name: obstacle_layer,    type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
#    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
